# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Spelling Request

# Model Form Field configuration
form: $/haegemon/frontendspelling/models/spellingrequest/fields.yaml

# Model Class name
modelClass: Haegemon\Frontendspelling\Models\SpellingRequest

# Default redirect location
defaultRedirect: haegemon/frontendspelling/spellingrequests

# Create page
create:
    title: Create Spelling Request
    redirect: haegemon/frontendspelling/spellingrequests/update/:id
    redirectClose: haegemon/frontendspelling/spellingrequests

# Update page
update:
    title: Edit Spelling Request
    redirect: haegemon/frontendspelling/spellingrequests
    redirectClose: haegemon/frontendspelling/spellingrequests

# Preview page
preview:
    title: Preview Spelling Request