# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Spelling Request

# Model Form Field configuration
form: $/cheerfulcab/frontendspelling/models/spellingrequest/fields.yaml

# Model Class name
modelClass: CheerfulLab\Frontendspelling\Models\SpellingRequest

# Default redirect location
defaultRedirect: cheerfulcab/frontendspelling/spellingrequests

# Create page
create:
    title: Create Spelling Request
    redirect: cheerfullab/frontendspelling/spellingrequests/update/:id
    redirectClose: cheerfullab/frontendspelling/spellingrequests

# Update page
update:
    title: Edit Spelling Request
    redirect: cheerfullab/frontendspelling/spellingrequests
    redirectClose: cheerfullab/frontendspelling/spellingrequests

# Preview page
preview:
    title: Preview Spelling Request